services:
  # PostgreSQL Database
  - type: pserv
    name: petkey-database
    plan: free
    databaseName: petkey_db
    databaseUser: petkey_user
    region: frankfurt

  # Django Backend
  - type: web
    name: petkey-backend
    runtime: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn petkey_api.wsgi:application"
    healthCheckPath: /api/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: petkey-database
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false

  # React Frontend
  - type: web
    name: petkey-frontend
    runtime: static
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
